/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tutorial.Gui;

import java.io.File;
import java.io.IOException;
import javax.swing.*;
import java.awt.*;

public class Gui {

    public static void startGui() {

       JFrame frame = new JFrame("Lets Go");
       frame.setLayout(null);
       frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       frame.setBounds(100,200,350,300);

       String image;

       try {
           image = new File("src/main/java/tutorial/resources/test_image.png").getCanonicalPath();
       } catch (IOException e) {
           System.out.print("The file 'resources/test_image.png' is not found, quiting now");
           return;
       }

       Container c = frame.getContentPane();
       JLabel label = new JLabel();
       label.setIcon(new ImageIcon(image));
       Dimension size = label.getPreferredSize();
       label.setBounds(50,30, size.width, size.height);

       c.add(label);
       frame.setVisible(true);

   }

   public static void zoomImage(Image image) {


   }

}



